apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fr1qp3ap7-go 
  janus-idp.io/tekton: fr1qp3ap7-go
  backstage.io/kubernetes-id: fr1qp3ap7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fr1qp3ap7-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  